---
title: "三角套利互動式頁面"
author: "109071015 QF24 張晁維"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    code_folding: hide
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html")
library(skimr)
library(kableExtra) 
library(tidyverse)
library(stringr)
library(lattice)
library(ggradar)
library(dplyr)
library(sjPlot)
#library(rsconnect)
```

```{r echo=TRUE}
data1 <- read.csv("FX_data.csv")
```

```{r echo=TRUE}
TA <- function(data1){
  index <- colnames(data1)[2:10]
  df <- data.frame(data1["Date"])
  for(i in 1:5){
    n0 <- str_sub(index[i], start=1, end=3)
    n1 <- str_sub(index[i], start=5, end=7)
    for(j in 6:9){
      if(str_sub(index[j], start=1, end=3)==n0){
        t0 <- as.numeric(data1[, j+1])
      }else if(str_sub(index[j], start=1, end=3)==n1){
        t1 <- as.numeric(data1[, j+1])
      }
    }
    dat <- data.frame(round(abs(t0/t1-data1[, i+1])
                            , digits=4))
    df <- cbind(df, dat)
  }
  colnames(df) <- c("Date", index[1:5])
  return(df)
}
```

```{r}
data2 <- TA(data1)
```

### (i)互動式: 查詢特定日期之匯率收盤價

```{r, echo=FALSE}
inputPanel(
  selectInput("date1", "Date: ", choices=data1["Date"])
)
renderTable({
  subset(data1, Date==input$date1)
})
```

### (ii)互動式: 查詢特定日期、特定貨幣以收盤價計價之套利空間

```{r, echo=FALSE}
index <- colnames(data1)[2:6]
inputPanel(
  selectInput("date2", "Date: ", choices=data2["Date"]),
  selectInput("country1", "Currencies", choices=index)
)
renderTable({
  subset(data2, Date==input$date2, select=input$country1)
})
renderTable({
  subset(data2, Date==input$date2)
})
```

### (iii)互動式: 特定貨幣以收盤價計價之套利空間分布視覺化

```{r aa7, echo=FALSE}
index <- colnames(data1)[2:6]
inputPanel(
  selectInput("country2", "Currency 1", choices=index)
)
renderPlot({
  plot(subset(data2, select=input$country2)
       , col=2
       , main="Arbutrage Opportunity Distribution")
})
renderPlot({
  boxplot(subset(data2, select=input$country2)
          , horizontal=T
          , main=input$country2)
})
```

### (iv)互動式: 視覺化比較不同貨幣組合之套利空間

```{r aa8, echo=FALSE}
inputPanel(
  selectInput("country3", "Currency 1", choices=index),
  selectInput("country4", "Currency 2", choices=rev(index))
)
renderPlot({
  plot(subset(data2, select=input$country3)
       , col=2
       , xaxt='n')
  par(new=T)
  plot(subset(data2, select=input$country4)
       , col=3
       , main="Comparison: \nGreen: currency 1   Red: currency 2\n(Comparable as the denominators are the same)")
})
renderPlot({
  datat <- data.frame(subset(data2, select=input$country3)
                     , subset(data2, select=input$country4
                              ))
  boxplot(datat, horizontal=T)
})
```

### (v)互動式: 視覺化比較套利空間分布與Chi-square PDF

#### PDF, Probability Density Function

```{r aa9}
#country: 8
index <- colnames(data1)[2:6]
inputPanel(
  selectInput("country9", "Currency 1", choices=index)
)
renderPlot({
  boxplot(dchisq(seq(from=0, to=0.1, by=0.01)
                 , df=1)*0.05
          , horizontal = T)
  par(new=T)
  plot(subset(data2, select=input$country9)
       , col=2
       , main="Arbutrage Opportunity Distribution\nwith chisq(1)*0.05"
       , xaxt='n'
       , xlim=c(0, 0.1))
})
```
